# Generated by Django 4.2.5 on 2023-12-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_market_data',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
