# Generated by Django 4.2.5 on 2023-12-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_alter_stock_market_data_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock_market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
                ('trade_code', models.CharField(max_length=30)),
                ('high', models.CharField(max_length=30)),
                ('low', models.CharField(max_length=30)),
                ('open', models.CharField(max_length=30)),
                ('close', models.CharField(max_length=30)),
                ('volume', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='stock_market_data',
        ),
    ]
