# Generated by Django 4.2.5 on 2023-12-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_stock_market_delete_stock_market_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_market',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
