# Generated by Django 4.2.5 on 2023-12-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_alter_stock_market_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='back_mart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=30)),
                ('trade_code', models.CharField(max_length=30)),
                ('high', models.CharField(max_length=30)),
                ('low', models.CharField(max_length=30)),
                ('open', models.CharField(max_length=30)),
                ('close', models.CharField(max_length=30)),
                ('volume', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='stock_market',
        ),
    ]
